<?php

use MClassic\Datatables\Datatables;
use MClassic\Datatables\Engine\ProtocolEngine;

class ProtocolEngineTest extends PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp();
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function test_new_output()
    {
        $datatables = new Datatables([], ['sEcho' => 123]);
        $engine = $datatables->getProtocol();
        $this->assertEquals(ProtocolEngine::VERSION_1, $engine->version(), 'Unable to match protocol version');
    }
}
